context:
  version: "8.0.0"

package:
  name: ava
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ava/-/ava-${{ version }}.tgz
  sha256: 2c9cd073fedd28db01e78a148874f0399a39dc2c151b441fa3010d360bb1e3d7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ava --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: Node.js test runner that lets you develop with confidence
  homepage: https://github.com/avajs/ava
  repository: https://github.com/avajs/ava

extra:
  recipe-maintainers:
    - danielnachun
