context:
  version: 6.1.3

package:
  name: ava
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ava/-/ava-${{ version }}.tgz
  sha256: 5da10da1e4217a65831a1b5be6be2c513530a50dc0aa62bda196a337f343a8ff

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ava --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: Node.js test runner that lets you develop with confidence
  homepage: https://github.com/avajs/ava
  repository: https://github.com/avajs/ava

extra:
  recipe-maintainers:
    - danielnachun
