context:
  version: "7.0.0"

package:
  name: ava
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ava/-/ava-${{ version }}.tgz
  sha256: 91463ed6c3ad9f44b27d7d992891d5b442a4acc44b86111f32a5c3b0d40fdeda

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ava --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: Node.js test runner that lets you develop with confidence
  homepage: https://github.com/avajs/ava
  repository: https://github.com/avajs/ava

extra:
  recipe-maintainers:
    - danielnachun
