context:
  version: "8.0.1"

package:
  name: ava
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ava/-/ava-${{ version }}.tgz
  sha256: 101c0e1915073ce89ae24a01ab4cc83f61e4ea891da6aa1c9af90517cb4144a0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ava --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: Node.js test runner that lets you develop with confidence
  homepage: https://github.com/avajs/ava
  repository: https://github.com/avajs/ava

extra:
  recipe-maintainers:
    - danielnachun
