context:
  version: "6.4.0"

package:
  name: ava
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/ava/-/ava-${{ version }}.tgz
  sha256: 6c57b2ccf6208ae46a620cee379b55c8c7fb501a54675066bdaa87b444c2fc53

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ava --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: Node.js test runner that lets you develop with confidence
  homepage: https://github.com/avajs/ava
  repository: https://github.com/avajs/ava

extra:
  recipe-maintainers:
    - danielnachun
